name: Run UI Tests

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore SauceDemoTests.UI/SauceDemoTests.UI.csproj

      - name: Build
        run: dotnet build SauceDemoTests.UI/SauceDemoTests.UI.csproj --no-restore

      - name: Run tests
        run: dotnet test SauceDemoTests.UI/SauceDemoTests.UI.csproj --no-build --logger "trx"
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Install Allure CLI
        if: always()
        run: npm install -g allure-commandline --save-dev

      - name: Generate Allure Report
        if: always()
        run: allure generate SauceDemoTests.UI/bin/Debug/net8.0/allure-results --clean -o allure-report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report